#!/usr/bin/env bash
# Execute local implementation tickets in dependency-gated waves.
#
# Every ticket in a wave receives its own linked Git worktree, branch,
# loop.sh process, campaign lock, and state directory. Worktrees are
# created sequentially to avoid racing Git's worktree administration, then
# their loops run concurrently. After a wave succeeds, the ticket tips are
# merged one at a time into a detached integration worktree. The merged tree
# must be conflict-free and pass the integration verification command before
# the integration branch advances or another wave starts.
#
# The waves are computed from the ticket files in .scratch/tickets. Each
# ticket may declare its blockers with a `Blocked by:` line containing ticket
# IDs or numeric prefixes, such as `Blocked by: 01, 03-feature`. A ticket sits
# in the wave after the latest wave containing one of its blockers.
#
# Successful ticket branches and the campaign integration branch are retained
# for audit and recovery. At the end of a successful campaign, the
# target branch is fast-forwarded or merged to the integration commit, then
# successful worktrees are removed and pruned unless KEEP_WORKTREES=1 is set.
set -euo pipefail
umask 077

export LC_ALL=C
export LANG=C
export TZ=UTC
export GIT_PAGER=cat
export PAGER=cat
export GIT_TERMINAL_PROMPT=0
export NO_COLOR=1
export CLICOLOR=0

TOOL_DIR="$(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly TOOL_DIR
# shellcheck source=shared/process.sh
. "$TOOL_DIR/shared/process.sh"
ROOT_DIR="$(git -C "$TOOL_DIR" rev-parse --show-toplevel)"
readonly ROOT_DIR

readonly LOOP_RELATIVE_PATH="scripts/local-ticket-loop/loop.sh"
readonly TICKET_RELATIVE_DIR="${TICKET_RELATIVE_DIR:-.scratch/tickets}"
TICKET_DENY_PATH_PATTERN="$(printf '%s' "$TICKET_RELATIVE_DIR" | sed 's/[.[\*^$()+?{}|]/\\&/g; s#/#\\/#g')"
readonly TICKET_DENY_PATH_PATTERN
readonly DEFAULT_VERIFY_COMMAND="swift build --build-tests && swift test"
readonly INTEGRATION_VERIFY_COMMAND="${INTEGRATION_VERIFY_COMMAND:-$DEFAULT_VERIFY_COMMAND}"
readonly TICKET_VERIFY_COMMAND="${TICKET_VERIFY_COMMAND:-$INTEGRATION_VERIFY_COMMAND}"
readonly DEFAULT_BASE_BRANCH="${DEFAULT_BASE_BRANCH:-feat/debtmap}"
readonly MERGE_BACK_BRANCH="${MERGE_BACK_BRANCH:-feat/debtmap}"
readonly INTEGRATION_REPAIR_COMMAND="${INTEGRATION_REPAIR_COMMAND:-}"
readonly INTEGRATION_REPAIR_TIMEOUT_SECONDS="${INTEGRATION_REPAIR_TIMEOUT_SECONDS:-3600}"
readonly KEEP_WORKTREES="${KEEP_WORKTREES:-0}"
readonly DENY_PATH_PATTERNS="${RALPH_DENY_PATH_PATTERNS:-^\.git/|^\.github/|^$TICKET_DENY_PATH_PATTERN/|^scripts/local-ticket-loop/}"

INTEGRATION_COMMIT=""
CAMPAIGN_ID="${CAMPAIGN_ID:-}"
CAMPAIGN_LOG_DIR=""
WORKTREE_ROOT="${WORKTREE_ROOT:-}"
INTEGRATION_BRANCH="${INTEGRATION_BRANCH:-}"
RESUME_CAMPAIGN=0

usage() {
	cat <<'EOF'
Usage: scripts/local-ticket-loop/proposed-loop.sh [--plan | --run | --resume <campaign-id>]

Without arguments or with --run, creates isolated linked Git worktrees, runs one loop.sh
process per ticket in parallel within each wave, and integrates each successful wave through a
sequential merge and verification gate. --plan prints the dependency waves without changing
repository state.

--resume continues a campaign that was interrupted. It adopts the campaign's existing
integration branch as its baseline, so every wave that already integrated is skipped rather
than redone. A ticket whose branch already exists is resumed in its own worktree: any
uncommitted work is first committed as a labelled checkpoint, which becomes the baseline the
agent continues from. A ticket with no branch yet starts fresh. --resume does not update the
harness inside an existing ticket worktree; merge the harness change into the ticket branch
first if the interruption was caused by the harness itself.

Environment:
  CAMPAIGN_ID                 Unique branch namespace; generated by default
  BASE_REVISION               Starting Git revision; default feat/debtmap (rejected with --resume)
  TICKET_RELATIVE_DIR         Ticket directory; default .scratch/tickets
  WORKTREE_ROOT               Isolated checkout parent; default under TMPDIR
  INTEGRATION_BRANCH          Campaign branch; generated by default
  MERGE_BACK_BRANCH           Destination branch advanced after success; default feat/debtmap
  TICKET_VERIFY_COMMAND       Per-ticket loop verification command
  INTEGRATION_VERIFY_COMMAND  Merged-wave verification command
  INTEGRATION_REPAIR_COMMAND  Optional conflict resolver run inside the integration worktree
  INTEGRATION_REPAIR_TIMEOUT_SECONDS  Conflict-repair timeout; default 3600
  KEEP_WORKTREES              1 to retain successful worktrees; default 0

The current checkout and BASE_REVISION must be clean and must already contain
the ticket files and loop harness. Failed or conflicted wave worktrees are kept
Successful branches and the integration branch are always kept.
EOF
}

note() {
	printf 'ticket waves: %s\n' "$*" >&2
}

fail() {
	note "ERROR: $*"
	exit 1
}

require_command() {
	command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"
}

print_wave() {
	local number="$1"
	shift
	printf 'wave %s:' "$number"
	printf ' %s' "$@"
	printf '\n'
}

ticket_id_from_path() {
	basename "$1" .md
}

ticket_ids_from_worktree() {
	local file found=0
	for file in "$ROOT_DIR/$TICKET_RELATIVE_DIR"/*.md; do
		[[ -e "$file" ]] || continue
		found=1
		ticket_id_from_path "$file"
	done
	((found == 1)) || fail "no ticket files found in $TICKET_RELATIVE_DIR"
}

blocker_tokens_for_ticket() {
	local ticket="$1" file line token lowered
	file="$ROOT_DIR/$TICKET_RELATIVE_DIR/$ticket.md"
	line="$(sed -nE 's/^[[:space:]]*Blocked by:[[:space:]]*//p' "$file" | head -n 1)"
	[[ -n "$line" ]] || return 0
	printf '%s\n' "$line" | tr ',;' '  ' | tr -s '[:space:]' '\n' | while IFS= read -r token; do
		[[ -n "$token" ]] || continue
		lowered="$(printf '%s' "$token" | tr '[:upper:]' '[:lower:]')"
		case "$lowered" in
		none | no | n/a | -) continue ;;
		esac
		printf '%s\n' "$token"
	done
}

resolve_ticket_reference() {
	local token="$1" ids_file="$2" id match count=0
	while IFS= read -r id; do
		if [[ "$token" == "$id" ]]; then
			printf '%s\n' "$id"
			return 0
		fi
	done <"$ids_file"

	while IFS= read -r id; do
		case "$id" in
		"$token"-*)
			match="$id"
			count=$((count + 1))
			;;
		esac
	done <"$ids_file"

	case "$count" in
	1) printf '%s\n' "$match" ;;
	0) fail "ticket blocker does not match any ticket: $token" ;;
	*) fail "ticket blocker is ambiguous: $token" ;;
	esac
}

ticket_blockers() {
	local ticket="$1" ids_file="$2" token
	while IFS= read -r token; do
		[[ -n "$token" ]] || continue
		resolve_ticket_reference "$token" "$ids_file"
	done < <(blocker_tokens_for_ticket "$ticket") | LC_ALL=C sort -u
}

ticket_wave_from_schedule() {
	local ticket="$1" schedule_file="$2"
	awk -v ticket="$ticket" '$1 == ticket { print $2; found = 1; exit } END { exit found ? 0 : 1 }' "$schedule_file"
}

# As-soon-as-possible schedule of the ticket blocking graph. Each ticket's
# blockers come from its `Blocked by:` line.
print_plan() {
	local ids_file schedule_file total scheduled progress id blockers blocker
	local ready max_wave blocker_wave unscheduled wave actual_wave
	local -a tickets_in_wave=()

	ids_file="$(mktemp "${TMPDIR:-/tmp}/ticket-plan-ids.XXXXXX")"
	schedule_file="$(mktemp "${TMPDIR:-/tmp}/ticket-plan-schedule.XXXXXX")"
	: >"$schedule_file"
	ticket_ids_from_worktree >"$ids_file"
	total="$(wc -l <"$ids_file" | tr -d '[:space:]')"
	scheduled=0

	while ((scheduled < total)); do
		progress=0
		while IFS= read -r id; do
			if ticket_wave_from_schedule "$id" "$schedule_file" >/dev/null 2>&1; then
				continue
			fi

			ready=1
			max_wave=0
			blockers="$(ticket_blockers "$id" "$ids_file")"
			while IFS= read -r blocker; do
				[[ -n "$blocker" ]] || continue
				blocker_wave="$(ticket_wave_from_schedule "$blocker" "$schedule_file" 2>/dev/null || true)"
				if [[ -z "$blocker_wave" ]]; then
					ready=0
					break
				fi
				((blocker_wave > max_wave)) && max_wave="$blocker_wave"
			done <<EOF
$blockers
EOF

			if ((ready == 1)); then
				printf '%s\t%s\n' "$id" "$((max_wave + 1))" >>"$schedule_file"
				scheduled=$((scheduled + 1))
				progress=1
			fi
		done <"$ids_file"

		if ((progress == 0)); then
			unscheduled="$(while IFS= read -r id; do
				if ! ticket_wave_from_schedule "$id" "$schedule_file" >/dev/null 2>&1; then
					printf '%s ' "$id"
				fi
			done <"$ids_file")"
			rm -f "$ids_file" "$schedule_file"
			fail "ticket dependency graph has a cycle or unresolved blockers: $unscheduled"
		fi
	done

	max_wave="$(awk 'max < $2 { max = $2 } END { print max + 0 }' "$schedule_file")"
	wave=1
	while ((wave <= max_wave)); do
		tickets_in_wave=()
		while IFS= read -r id; do
			actual_wave="$(ticket_wave_from_schedule "$id" "$schedule_file")"
			[[ "$actual_wave" == "$wave" ]] && tickets_in_wave+=("$id")
		done <"$ids_file"
		print_wave "$wave" "${tickets_in_wave[@]}"
		wave=$((wave + 1))
	done

	rm -f "$ids_file" "$schedule_file"
}

absolute_git_common_dir() {
	local common
	common="$(git -C "$ROOT_DIR" rev-parse --git-common-dir)"
	case "$common" in
	/*) printf '%s\n' "$common" ;;
	*) (cd "$ROOT_DIR/$common" && pwd -P) ;;
	esac
}

validate_identifier() {
	local label="$1" value="$2"
	case "$value" in
	'' | *[!A-Za-z0-9._/-]*) fail "$label contains unsupported characters: $value" ;;
	esac
}

# Working-tree changes that belong to the repository. The agent harness writes
# a per-run record under .agents/evidence/ for every `claude -p` call, including
# the ones this orchestrator starts; counting it would make a campaign refuse to
# begin, and would fail a wave after its own repair step.
worktree_dirt() {
	git -C "$1" status --porcelain | grep -vE '^\?\? \.agents/evidence/' || true
}

realpath_of() {
	python3 -c 'import os, sys; print(os.path.realpath(sys.argv[1]))' "$1"
}

preflight() {
	require_command git
	require_command swift
	require_command perl
	require_command jq
	require_command python3
	[[ "$INTEGRATION_REPAIR_TIMEOUT_SECONDS" =~ ^[1-9][0-9]*$ ]] ||
		fail "INTEGRATION_REPAIR_TIMEOUT_SECONDS must be a positive integer"

	[[ -x "$ROOT_DIR/$LOOP_RELATIVE_PATH" ]] || fail "loop harness is missing or not executable: $LOOP_RELATIVE_PATH"
	[[ "$KEEP_WORKTREES" == 0 || "$KEEP_WORKTREES" == 1 ]] || fail "KEEP_WORKTREES must be 0 or 1"

	if [[ -n "$(worktree_dirt "$ROOT_DIR")" ]]; then
		worktree_dirt "$ROOT_DIR" >&2
		fail "current checkout is dirty; commit the tickets and harness before --run"
	fi

	if [[ "$RESUME_CAMPAIGN" == 1 ]]; then
		[[ -z "${BASE_REVISION:-}" ]] ||
			fail "BASE_REVISION cannot be combined with --resume; the campaign's integration branch is the baseline"
	fi

	CAMPAIGN_ID="${CAMPAIGN_ID:-$(date -u +%Y%m%dT%H%M%SZ)-$$}"
	validate_identifier CAMPAIGN_ID "$CAMPAIGN_ID"
	INTEGRATION_BRANCH="${INTEGRATION_BRANCH:-local-ticket-loop/$CAMPAIGN_ID/integration}"
	validate_identifier INTEGRATION_BRANCH "$INTEGRATION_BRANCH"
	validate_identifier MERGE_BACK_BRANCH "$MERGE_BACK_BRANCH"
	git -C "$ROOT_DIR" show-ref --verify --quiet "refs/heads/$MERGE_BACK_BRANCH" ||
		fail "merge-back branch is missing: $MERGE_BACK_BRANCH"

	if [[ "$RESUME_CAMPAIGN" == 1 ]]; then
		# The integration branch already carries every wave this campaign
		# integrated before it was interrupted. Adopting it as the baseline is
		# what makes those waves skip instead of being redone.
		git -C "$ROOT_DIR" show-ref --verify --quiet "refs/heads/$INTEGRATION_BRANCH" ||
			fail "no such campaign to resume; integration branch is missing: $INTEGRATION_BRANCH"
		INTEGRATION_COMMIT="$(git -C "$ROOT_DIR" rev-parse --verify "refs/heads/$INTEGRATION_BRANCH^{commit}")"
	else
		local baseline="${BASE_REVISION:-$DEFAULT_BASE_BRANCH}"
		if [[ -z "${BASE_REVISION:-}" ]]; then
			git -C "$ROOT_DIR" show-ref --verify --quiet "refs/heads/$DEFAULT_BASE_BRANCH" ||
				fail "default base branch is missing: $DEFAULT_BASE_BRANCH"
		fi
		INTEGRATION_COMMIT="$(git -C "$ROOT_DIR" rev-parse --verify "${baseline}^{commit}")" ||
			fail "BASE_REVISION is not a commit: $baseline"
		if git -C "$ROOT_DIR" show-ref --verify --quiet "refs/heads/$INTEGRATION_BRANCH"; then
			fail "integration branch already exists: $INTEGRATION_BRANCH"
		fi
	fi

	local common_git_dir
	common_git_dir="$(absolute_git_common_dir)"
	CAMPAIGN_LOG_DIR="$common_git_dir/local-ticket-loop/wave-campaigns/$CAMPAIGN_ID"
	local requested_worktree_root
	requested_worktree_root="${WORKTREE_ROOT:-${TMPDIR:-/tmp}/swift-deep-research-ticket-waves-$CAMPAIGN_ID}"
	[[ "$requested_worktree_root" = /* ]] || fail "WORKTREE_ROOT must be an absolute path"
	WORKTREE_ROOT="$(realpath_of "$requested_worktree_root")"
	[[ "$WORKTREE_ROOT" != "$ROOT_DIR" && "$WORKTREE_ROOT" != "$ROOT_DIR/"* ]] ||
		fail "WORKTREE_ROOT resolves inside the repository"
	[[ "$WORKTREE_ROOT" != "$common_git_dir" && "$WORKTREE_ROOT" != "$common_git_dir/"* ]] ||
		fail "WORKTREE_ROOT resolves inside the Git common directory"
	local existing_worktree canonical_worktree
	while IFS= read -r existing_worktree; do
		canonical_worktree="$(realpath_of "$existing_worktree")"
		[[ "$WORKTREE_ROOT" != "$canonical_worktree" && "$WORKTREE_ROOT" != "$canonical_worktree/"* ]] ||
			fail "WORKTREE_ROOT resolves inside an existing worktree: $canonical_worktree"
	done < <(git -C "$ROOT_DIR" worktree list --porcelain | sed -n 's/^worktree //p')
	if [[ "$RESUME_CAMPAIGN" == 1 ]]; then
		[[ -d "$WORKTREE_ROOT" ]] || fail "resumed campaign has no worktree root: $WORKTREE_ROOT"
	else
		[[ ! -e "$WORKTREE_ROOT" ]] || fail "WORKTREE_ROOT already exists: $WORKTREE_ROOT"
	fi

	local ticket
	while IFS= read -r ticket; do
		[[ -f "$ROOT_DIR/$TICKET_RELATIVE_DIR/$ticket.md" ]] || fail "ticket file missing: $ticket"
		git -C "$ROOT_DIR" cat-file -e "$INTEGRATION_COMMIT:$TICKET_RELATIVE_DIR/$ticket.md" 2>/dev/null ||
			fail "ticket is not present in BASE_REVISION: $ticket"
	done < <(print_plan | tr ' ' '\n' | grep -E '^[0-9][0-9]-')

	mkdir -p "$CAMPAIGN_LOG_DIR" "$WORKTREE_ROOT"
	if [[ "$RESUME_CAMPAIGN" != 1 ]]; then
		git -C "$ROOT_DIR" branch "$INTEGRATION_BRANCH" "$INTEGRATION_COMMIT"
	fi

	if [[ "$RESUME_CAMPAIGN" == 1 ]]; then
		note "resuming campaign $CAMPAIGN_ID"
	else
		note "campaign $CAMPAIGN_ID"
	fi
	note "baseline $INTEGRATION_COMMIT"
	note "integration branch $INTEGRATION_BRANCH"
	note "per-ticket loop $LOOP_RELATIVE_PATH"
	note "worktrees $WORKTREE_ROOT"
	note "logs $CAMPAIGN_LOG_DIR"
}

prepare_ticket_worktree() {
	local wave="$1" ticket="$2" baseline="$3" output_file="$4"
	local wave_dir="$WORKTREE_ROOT/wave-$wave"
	local path="$wave_dir/$ticket"
	local branch="local-ticket-loop/$CAMPAIGN_ID/$ticket"

	mkdir -p "$wave_dir"
	if git -C "$ROOT_DIR" show-ref --verify --quiet "refs/heads/$branch"; then
		if [[ "$RESUME_CAMPAIGN" != 1 ]]; then
			fail "ticket branch already exists: $branch"
		fi
		adopt_ticket_worktree "$ticket" "$branch" "$path" "$baseline"
	else
		git -C "$ROOT_DIR" worktree add --quiet -b "$branch" "$path" "$baseline"
	fi
	printf '%s\t%s\t%s\n' "$ticket" "$branch" "$path" >"$output_file"
}

# Reattach a ticket branch left behind by an interrupted campaign and hand the
# agent its own unfinished work as the baseline, so it continues rather than
# restarting. Uncommitted work is committed first, because the per-ticket loop
# requires a clean worktree and would otherwise refuse to run at all.
adopt_ticket_worktree() {
	local ticket="$1" branch="$2" path="$3" baseline="$4"
	local registered tip existing

	git -C "$ROOT_DIR" merge-base --is-ancestor "$baseline" "refs/heads/$branch^{commit}" ||
		fail "cannot resume ticket $ticket: branch $branch does not descend from the campaign baseline"

	registered=0
	while IFS= read -r existing; do
		[[ "$(realpath_of "$existing")" != "$(realpath_of "$path")" ]] || registered=1
	done < <(git -C "$ROOT_DIR" worktree list --porcelain | sed -n 's/^worktree //p')

	if ((registered == 0)); then
		[[ ! -e "$path" ]] ||
			fail "cannot resume ticket $ticket: $path exists but is not a registered worktree"
		git -C "$ROOT_DIR" worktree add --quiet "$path" "$branch"
	fi

	[[ "$(git -C "$path" rev-parse --abbrev-ref HEAD)" == "$branch" ]] ||
		fail "cannot resume ticket $ticket: worktree $path is not on $branch"

	checkpoint_interrupted_work "$ticket" "$path"

	tip="$(git -C "$path" rev-parse HEAD)"
	note "resuming ticket $ticket in place at $tip"
}

# Commit whatever an interrupted agent left uncommitted, labelled so the history
# does not present unreviewed work as finished. Protected paths are never
# checkpointed: work there is the harness defending itself, not ticket progress.
checkpoint_interrupted_work() {
	local ticket="$1" path="$2" dirt

	dirt="$(worktree_dirt "$path")"
	[[ -n "$dirt" ]] || return 0

	if printf '%s\n' "$dirt" | sed 's/^...//' | grep -qE "$DENY_PATH_PATTERNS"; then
		printf '%s\n' "$dirt" >&2
		fail "cannot resume ticket $ticket: uncommitted changes touch a protected path"
	fi

	git -C "$path" add -A -- . ':(exclude).agents/evidence'
	if git -C "$path" diff --cached --quiet; then
		return 0
	fi
	git -C "$path" commit -q -m "wip($ticket): checkpoint interrupted work from campaign $CAMPAIGN_ID

The ticket run was interrupted before it reported completion. This commit is
the resume baseline, not finished work: it is unreviewed and the ticket's
acceptance criteria remain unchecked."
	note "checkpointed interrupted work for ticket $ticket"
}

archive_and_remove_worktree() {
	local ticket="$1" path="$2"
	local worktree_git_dir archive_dir
	worktree_git_dir="$(git -C "$path" rev-parse --absolute-git-dir)"
	archive_dir="$CAMPAIGN_LOG_DIR/$ticket-state"
	if [[ -d "$worktree_git_dir/local-ticket-loop" ]]; then
		cp -R "$worktree_git_dir/local-ticket-loop" "$archive_dir"
	fi
	if [[ "$KEEP_WORKTREES" == 1 ]]; then
		note "retaining successful worktree: $path"
		return
	fi
	if ! git -C "$ROOT_DIR" worktree remove "$path"; then
		note "could not remove cleanly; retaining worktree: $path"
		return
	fi
	git -C "$ROOT_DIR" worktree prune
}


# Merges one ticket tip into the detached integration worktree. A conflict is
# handed to INTEGRATION_REPAIR_COMMAND when one is configured; otherwise the
# worktree is left mid-merge so the conflict can be inspected by hand.
merge_tip_into_integration() {
	local wave="$1" path="$2" ticket="$3" tip="$4" log="$5"
	local status=0

	if git -C "$path" merge --no-ff --no-edit \
		-m "integrate(local-ticket-loop): campaign $CAMPAIGN_ID wave $wave ticket $ticket" \
		"$tip" >>"$log" 2>&1; then
		return 0
	fi

	[[ -n "$INTEGRATION_REPAIR_COMMAND" ]] || {
		git -C "$path" diff --name-only --diff-filter=U >>"$log" 2>&1 || true
		tail -n 100 "$log" >&2 || true
		fail "wave $wave merge of ticket $ticket conflicted and no INTEGRATION_REPAIR_COMMAND is set; worktree retained at $path"
	}

	note "wave $wave merge of $ticket conflicted; running integration repair in $path"
	(
		cd "$path"
		INTEGRATION_WAVE="$wave" INTEGRATION_TICKET="$ticket" \
			run_with_timeout "$INTEGRATION_REPAIR_TIMEOUT_SECONDS" \
			bash -o pipefail -c "$INTEGRATION_REPAIR_COMMAND"
	) >>"$log" 2>&1 || status=$?
	((status == 0)) || {
		tail -n 200 "$log" >&2 || true
		fail "wave $wave integration repair failed with status $status; worktree retained at $path"
	}
	[[ -z "$(git -C "$path" diff --name-only --diff-filter=U)" ]] ||
		fail "wave $wave integration repair left unresolved conflicts; worktree retained at $path"
	[[ -z "$(worktree_dirt "$path")" ]] ||
		fail "wave $wave integration repair left the worktree dirty; worktree retained at $path"
}

# Merges every ticket tip onto the wave baseline in a detached worktree, then
# verifies the merged tree in that same worktree. Prints the integration commit.
integrate_wave() {
	local wave="$1" baseline="$2"
	shift 2
	local -a entries=("$@")
	local path="$WORKTREE_ROOT/wave-$wave/integration"
	local log="$CAMPAIGN_LOG_DIR/wave-$wave-integration.log"
	local entry ticket tip commit

	git -C "$ROOT_DIR" worktree add --quiet --detach "$path" "$baseline"
	for entry in "${entries[@]}"; do
		ticket="${entry%%:*}"
		tip="${entry#*:}"
		merge_tip_into_integration "$wave" "$path" "$ticket" "$tip" "$log"
	done

	commit="$(git -C "$path" rev-parse HEAD)"
	for entry in "${entries[@]}"; do
		ticket="${entry%%:*}"
		if git -C "$path" show "HEAD:$TICKET_RELATIVE_DIR/$ticket.md" |
			grep -qE '^[[:space:]]*[-*] \[ \]'; then
			fail "wave $wave integration lost the completed state for ticket $ticket; worktree retained at $path"
		fi
	done

	note "wave $wave verifying integrated commit $commit"
	if ! (cd "$path" && bash -o pipefail -c "$INTEGRATION_VERIFY_COMMAND") >>"$log" 2>&1; then
		tail -n 200 "$log" >&2 || true
		fail "wave $wave integration verification failed; worktree retained at $path"
	fi
	[[ "$(git -C "$path" rev-parse HEAD)" == "$commit" ]] ||
		fail "wave $wave verification moved the integration HEAD"
	[[ -z "$(worktree_dirt "$path")" ]] ||
		fail "wave $wave verification left the integration worktree dirty; worktree retained at $path"

	if ! git -C "$ROOT_DIR" worktree remove "$path"; then
		note "could not remove integration worktree: $path"
	else
		git -C "$ROOT_DIR" worktree prune
	fi
	printf '%s\n' "$commit"
}

ticket_is_open_at_commit() {
	local commit="$1" ticket="$2"
	git -C "$ROOT_DIR" show "$commit:$TICKET_RELATIVE_DIR/$ticket.md" |
		grep -qE '^[[:space:]]*[-*] \[ \]'
}

run_wave() {
	local wave="$1"
	shift
	local baseline="$INTEGRATION_COMMIT"
	local metadata_dir="$CAMPAIGN_LOG_DIR/wave-$wave-worktrees"
	local ticket metadata branch path tip
	local overall_rc=0
	local index=0
	local -a requested_tickets=("$@")
	local -a tickets=()
	local -a branches=()
	local -a paths=()
	local -a pids=()
	local -a entries=()

	for ticket in "${requested_tickets[@]}"; do
		if ticket_is_open_at_commit "$baseline" "$ticket"; then
			tickets+=("$ticket")
		else
			note "wave $wave ticket $ticket already complete at baseline; skipping"
		fi
	done
	if ((${#tickets[@]} == 0)); then
		note "wave $wave has no open tickets; skipping"
		return
	fi

	mkdir -p "$metadata_dir"
	note "wave $wave preparing ${#tickets[@]} isolated worktree(s) from $baseline"
	for ticket in "${tickets[@]}"; do
		metadata="$metadata_dir/$ticket.tsv"
		prepare_ticket_worktree "$wave" "$ticket" "$baseline" "$metadata"
		branches+=("$(cut -f2 "$metadata")")
		paths+=("$(cut -f3 "$metadata")")
	done

	note "wave $wave starting ${#tickets[@]} parallel loop invocation(s)"
	index=0
	for ticket in "${tickets[@]}"; do
		branch="${branches[$index]}"
		path="${paths[$index]}"
		(
			cd "$path"
			LOCAL_TICKET_DIR="$path/$TICKET_RELATIVE_DIR" \
				RALPH_EXPECTED_BRANCH="$branch" \
				RALPH_VERIFY_COMMAND="$TICKET_VERIFY_COMMAND" \
				RALPH_DENY_PATH_PATTERNS="$DENY_PATH_PATTERNS" \
				"$path/$LOOP_RELATIVE_PATH" "$ticket"
		) >"$CAMPAIGN_LOG_DIR/$ticket-runner.log" 2>&1 &
		pids+=("$!")
		index=$((index + 1))
	done

	index=0
	for ticket in "${tickets[@]}"; do
		if wait "${pids[$index]}"; then
			note "wave $wave ticket $ticket succeeded"
		else
			note "wave $wave ticket $ticket failed; see $CAMPAIGN_LOG_DIR/$ticket-runner.log"
			overall_rc=1
		fi
		index=$((index + 1))
	done
	((overall_rc == 0)) || fail "wave $wave failed; no integration was attempted and worktrees were retained"

	index=0
	for ticket in "${tickets[@]}"; do
		branch="${branches[$index]}"
		tip="$(git -C "$ROOT_DIR" rev-parse --verify "refs/heads/$branch^{commit}")"
		[[ "$tip" != "$baseline" ]] ||
			fail "ticket $ticket returned success without creating a commit"
		git -C "$ROOT_DIR" merge-base --is-ancestor "$baseline" "$tip" ||
			fail "ticket $ticket did not descend from wave $wave baseline"
		if git -C "$ROOT_DIR" diff --quiet "$baseline" "$tip" --; then
			fail "ticket $ticket returned success without a tree change"
		fi
		entries+=("$ticket:$tip")
		index=$((index + 1))
	done

	INTEGRATION_COMMIT="$(integrate_wave "$wave" "$baseline" "${entries[@]}")"
	git -C "$ROOT_DIR" branch -f "$INTEGRATION_BRANCH" "$INTEGRATION_COMMIT"

	index=0
	for ticket in "${tickets[@]}"; do
		archive_and_remove_worktree "$ticket" "${paths[$index]}"
		index=$((index + 1))
	done
	note "wave $wave passed; $INTEGRATION_BRANCH now points to $INTEGRATION_COMMIT"
}

advance_merge_back_branch() {
	local current_branch
	git -C "$ROOT_DIR" merge-base --is-ancestor "refs/heads/$MERGE_BACK_BRANCH" "$INTEGRATION_COMMIT" ||
		fail "cannot merge back: $MERGE_BACK_BRANCH is not an ancestor of $INTEGRATION_COMMIT"
	current_branch="$(git -C "$ROOT_DIR" rev-parse --abbrev-ref HEAD)"
	if [[ "$current_branch" == "$MERGE_BACK_BRANCH" ]]; then
		note "fast-forwarding checked-out branch $MERGE_BACK_BRANCH to $INTEGRATION_COMMIT"
		git -C "$ROOT_DIR" merge --ff-only "$INTEGRATION_COMMIT" >/dev/null
	else
		note "advancing branch $MERGE_BACK_BRANCH to $INTEGRATION_COMMIT"
		git -C "$ROOT_DIR" branch -f "$MERGE_BACK_BRANCH" "$INTEGRATION_COMMIT" >/dev/null
	fi
}

run_campaign() {
	preflight

	local wave_number line
	wave_number=0
	while IFS= read -r line; do
		wave_number=$((wave_number + 1))
		# shellcheck disable=SC2086 # the ticket list is a controlled literal.
		run_wave "$wave_number" ${line#wave*: }
	done < <(print_plan)

	advance_merge_back_branch

	printf 'Campaign complete.\nIntegration branch: %s\nIntegration commit: %s\nMerged back to: %s\nLogs: %s\n' \
		"$INTEGRATION_BRANCH" "$INTEGRATION_COMMIT" "$MERGE_BACK_BRANCH" "$CAMPAIGN_LOG_DIR"
}

case "${1:-}" in
--plan)
	(($# == 1)) || {
		usage >&2
		exit 2
	}
	print_plan
	;;
'' | --run)
	(($# <= 1)) || {
		usage >&2
		exit 2
	}
	run_campaign
	;;
--resume)
	(($# == 2)) || {
		usage >&2
		exit 2
	}
	RESUME_CAMPAIGN=1
	CAMPAIGN_ID="$2"
	run_campaign
	;;
--help | -h)
	usage
	;;
*)
	usage >&2
	exit 2
	;;
esac
